name: dp
channels:
  - conda-forge
  - bioconda
  - defaults
  - main
dependencies:
  - conda
  - python>3.9
  - pandas
  - numpy
  - biopython
  - peptides
  - rdkit
  - matplotlib
  - seaborn
  - catboost
